package lab6p2_hazielpavon;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ds_Portatil = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        Ds_Pantalla = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Ds_Bateria = new javax.swing.JTextField();
        Ds_portatil = new javax.swing.JButton();
        Ds_si = new javax.swing.JRadioButton();
        Ds_no = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        Ds_Estacionaria = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        Ds_botonestacionario = new javax.swing.JButton();
        Ds_NumeroControles = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Ds_Tipoconexion = new javax.swing.JTextField();
        Ds_Almacenamiento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Ds_Juegos = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Ds_Fechadeljuego = new com.toedter.calendar.JCalendar();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Ds_Cantidaddejuegos = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ds_Descripcion = new javax.swing.JTextArea();
        Ds_Preciodeljuego = new javax.swing.JTextField();
        Ds_Nombredelosjuegos = new javax.swing.JTextField();
        Ds_agregarjuegos = new javax.swing.JButton();
        Ds_Estadousado = new javax.swing.JRadioButton();
        Ds_Estadonuevo = new javax.swing.JRadioButton();
        Ds_Norentable = new javax.swing.JRadioButton();
        Ds_Rentableboton = new javax.swing.JRadioButton();
        Ds_botonagrgado = new javax.swing.JRadioButton();
        Ds_noagregado = new javax.swing.JRadioButton();
        Ds_Tipobottongroup = new javax.swing.ButtonGroup();
        Ds_Sekeccion = new javax.swing.ButtonGroup();
        Ds_Menuprincipal = new javax.swing.JPopupMenu();
        Ds_ListarJuegos = new javax.swing.JMenuItem();
        Ds_Modificarconsolas = new javax.swing.JMenuItem();
        Ds_EliminarConsolas = new javax.swing.JMenuItem();
        Ds_Rentable = new javax.swing.ButtonGroup();
        Ds_Estado = new javax.swing.ButtonGroup();
        Ds_Agregado = new javax.swing.ButtonGroup();
        Ds_ListarLosjuegos = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Ds_List = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Ds_Identificacion = new javax.swing.JTextField();
        Ds_Precio = new javax.swing.JTextField();
        Ds_Fabricante = new javax.swing.JTextField();
        Ds_Modelo = new javax.swing.JTextField();
        Ds_AgregarConsolas = new javax.swing.JButton();
        Ds_RadioPortatil = new javax.swing.JRadioButton();
        Ds_EstacionariaRadio = new javax.swing.JRadioButton();
        Ds_Juegosdisponibles = new javax.swing.JSpinner();
        Ds_Anosuso = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        Ds_Tabladeconsolas = new javax.swing.JTable();

        Ds_Pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ds_PantallaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setText("Estuche:");

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel11.setText("Tamaño de pantalla:");

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel12.setText("Bateria:");

        Ds_portatil.setText("Agregar");
        Ds_portatil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ds_portatilMouseClicked(evt);
            }
        });

        Ds_Sekeccion.add(Ds_si);
        Ds_si.setText("SI");

        Ds_Sekeccion.add(Ds_no);
        Ds_no.setText("No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Ds_Pantalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(Ds_Bateria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Ds_si, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ds_no, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Ds_portatil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Ds_Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Ds_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Ds_si)
                    .addComponent(Ds_no))
                .addGap(34, 34, 34)
                .addComponent(Ds_portatil)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel13.setText("Portatil");

        javax.swing.GroupLayout Ds_PortatilLayout = new javax.swing.GroupLayout(Ds_Portatil.getContentPane());
        Ds_Portatil.getContentPane().setLayout(Ds_PortatilLayout);
        Ds_PortatilLayout.setHorizontalGroup(
            Ds_PortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ds_PortatilLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel13)
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(Ds_PortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Ds_PortatilLayout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
        );
        Ds_PortatilLayout.setVerticalGroup(
            Ds_PortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ds_PortatilLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(Ds_PortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Ds_PortatilLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        Ds_botonestacionario.setText("Agregar");
        Ds_botonestacionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ds_botonestacionarioMouseClicked(evt);
            }
        });
        Ds_botonestacionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ds_botonestacionarioActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel15.setText("Tipo de conexion:");

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel16.setText("Numero de controles:");

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel17.setText("Almacenamiento:");

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel18.setText("Estacionaria");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ds_NumeroControles, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ds_Almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ds_Tipoconexion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Ds_botonestacionario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Ds_NumeroControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Ds_Almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Ds_Tipoconexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(Ds_botonestacionario)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Ds_EstacionariaLayout = new javax.swing.GroupLayout(Ds_Estacionaria.getContentPane());
        Ds_Estacionaria.getContentPane().setLayout(Ds_EstacionariaLayout);
        Ds_EstacionariaLayout.setHorizontalGroup(
            Ds_EstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(Ds_EstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Ds_EstacionariaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Ds_EstacionariaLayout.setVerticalGroup(
            Ds_EstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(Ds_EstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Ds_EstacionariaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Ds_Juegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ds_JuegosMouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel19.setText("Juegos");

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel20.setText("Nombre:");

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel21.setText("Descripcion:");

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel22.setText("Fecha:");

        jLabel23.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel23.setText("Cantidad:");

        jLabel24.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel24.setText("Precio:");

        jLabel25.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel25.setText("Estado:");

        jLabel26.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel26.setText("Agregado:");

        jLabel27.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel27.setText("Rentable: ");

        Ds_Descripcion.setColumns(20);
        Ds_Descripcion.setRows(5);
        jScrollPane3.setViewportView(Ds_Descripcion);

        Ds_agregarjuegos.setText("Agregar");
        Ds_agregarjuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ds_agregarjuegosMouseClicked(evt);
            }
        });

        Ds_Estado.add(Ds_Estadousado);
        Ds_Estadousado.setText("Usado");

        Ds_Estado.add(Ds_Estadonuevo);
        Ds_Estadonuevo.setText("Nuevo");

        Ds_Rentable.add(Ds_Norentable);
        Ds_Norentable.setText("No Rentable");

        Ds_Rentable.add(Ds_Rentableboton);
        Ds_Rentableboton.setText("Rentable");

        Ds_Agregado.add(Ds_botonagrgado);
        Ds_botonagrgado.setText("Agregado");
        Ds_botonagrgado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ds_botonagrgadoActionPerformed(evt);
            }
        });

        Ds_Agregado.add(Ds_noagregado);
        Ds_noagregado.setText("No agregado");
        Ds_noagregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ds_noagregadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addComponent(Ds_Nombredelosjuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel23))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(Ds_Preciodeljuego, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(jLabel26))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ds_Fechadeljuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(Ds_agregarjuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Ds_Estadonuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ds_Estadousado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(Ds_Cantidaddejuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(173, 173, 173)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Ds_Rentableboton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ds_Norentable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(Ds_noagregado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ds_botonagrgado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(431, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(Ds_Nombredelosjuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(Ds_Estadousado)
                            .addComponent(Ds_Estadonuevo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(Ds_Cantidaddejuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(Ds_Norentable)
                            .addComponent(Ds_Rentableboton))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ds_Preciodeljuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Ds_botonagrgado)
                                .addComponent(Ds_noagregado)))))
                .addGap(47, 47, 47)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ds_Fechadeljuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(Ds_agregarjuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(390, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout Ds_JuegosLayout = new javax.swing.GroupLayout(Ds_Juegos.getContentPane());
        Ds_Juegos.getContentPane().setLayout(Ds_JuegosLayout);
        Ds_JuegosLayout.setHorizontalGroup(
            Ds_JuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ds_JuegosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Ds_JuegosLayout.setVerticalGroup(
            Ds_JuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ds_JuegosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Ds_ListarJuegos.setText("Listar Juegos");
        Ds_ListarJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ds_ListarJuegosActionPerformed(evt);
            }
        });
        Ds_Menuprincipal.add(Ds_ListarJuegos);

        Ds_Modificarconsolas.setText("Modificar consolas");
        Ds_Menuprincipal.add(Ds_Modificarconsolas);

        Ds_EliminarConsolas.setText("Eliminar consolas");
        Ds_Menuprincipal.add(Ds_EliminarConsolas);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel28.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel28.setText("Lista de juegos");

        jScrollPane4.setViewportView(Ds_List);

        jButton1.setText("Agregar juegos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel28))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel28)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout Ds_ListarLosjuegosLayout = new javax.swing.GroupLayout(Ds_ListarLosjuegos.getContentPane());
        Ds_ListarLosjuegos.getContentPane().setLayout(Ds_ListarLosjuegosLayout);
        Ds_ListarLosjuegosLayout.setHorizontalGroup(
            Ds_ListarLosjuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
            .addGroup(Ds_ListarLosjuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Ds_ListarLosjuegosLayout.setVerticalGroup(
            Ds_ListarLosjuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(Ds_ListarLosjuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Consolas");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Precio:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Identificacion:");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Fabricante:");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Años de uso:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Juegos disponibles:");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("Tipo:");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("Modelo:");

        Ds_AgregarConsolas.setText("Agregar");
        Ds_AgregarConsolas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ds_AgregarConsolasMouseClicked(evt);
            }
        });

        Ds_Tipobottongroup.add(Ds_RadioPortatil);
        Ds_RadioPortatil.setText("Portatil");

        Ds_Tipobottongroup.add(Ds_EstacionariaRadio);
        Ds_EstacionariaRadio.setText("Estacionaria");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Consolas");

        Ds_Tabladeconsolas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Años ", "Fabricante", "Precio", "Modelo", "Juegos disponibles", "Tipo", "Identificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Ds_Tabladeconsolas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ds_TabladeconsolasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ds_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ds_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ds_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ds_Fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Ds_RadioPortatil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ds_EstacionariaRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(Ds_Anosuso, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ds_Juegosdisponibles)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Ds_AgregarConsolas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(388, 388, 388))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel9)
                        .addGap(315, 315, 315))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Ds_Tabladeconsolas, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Ds_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ds_Tabladeconsolas, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(Ds_AgregarConsolas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Ds_Fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Ds_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(Ds_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Ds_RadioPortatil)
                                    .addComponent(Ds_EstacionariaRadio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Ds_Anosuso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Ds_Juegosdisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(210, 210, 210))))
        );

        jTabbedPane1.addTab("Agregar consolas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ds_AgregarConsolasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ds_AgregarConsolasMouseClicked

        int id, uso, jdisp;
        String model, fab, tip;
        double prec;

        id = Integer.parseInt(Ds_Identificacion.getText());

        uso = (int) Ds_Anosuso.getValue();

        jdisp = (int) Ds_Juegosdisponibles.getValue();

        model = Ds_Modelo.getText();

        fab = Ds_Fabricante.getText();

        prec = Integer.parseInt(Ds_Precio.getText());

        if (Ds_EstacionariaRadio.isSelected()) {

            Ds_Estacionaria.pack();
            Ds_Estacionaria.setModal(true);
            Ds_Estacionaria.setLocationRelativeTo(null);
            Ds_Estacionaria.setVisible(true);

            tip = "Estacionaria";

            DefaultTableModel modelo = (DefaultTableModel) Ds_Tabladeconsolas.getModel();

            Object[] datos = new Object[8];

            datos[0] = uso;
            datos[1] = fab;
            datos[2] = prec;
            datos[3] = model;
            datos[4] = "";
            datos[5] = tip;
            datos[6] = id;

            modelo.addRow(datos);

            Ds_Tabladeconsolas.setModel(modelo);

            Consolas C = new Estacionaria(numcon, space, conex, id, fab, uso, prec, model);

            consolas.add(C);

        } else if (Ds_RadioPortatil.isSelected()) {

            Ds_Portatil.pack();
            Ds_Portatil.setModal(true);
            Ds_Portatil.setLocationRelativeTo(null);
            Ds_Portatil.setVisible(true);

            tip = "Portatil";

            DefaultTableModel modelo = (DefaultTableModel) Ds_Tabladeconsolas.getModel();

            Object[] datos = new Object[8];

            datos[0] = uso;
            datos[1] = fab;
            datos[2] = prec;
            datos[3] = model;
            datos[4] = "";
            datos[5] = tip;
            datos[6] = id;

            modelo.addRow(datos);

            Ds_Tabladeconsolas.setModel(modelo);

            Consolas C = new Portatil(tampan, bat, estuche, id, fab, uso, prec, model);

            consolas.add(C);

        }


    }//GEN-LAST:event_Ds_AgregarConsolasMouseClicked

    private void Ds_portatilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ds_portatilMouseClicked

        tampan = Ds_Pantalla.getText();
        bat = Integer.parseInt(Ds_Bateria.getText());

        if (Ds_si.isSelected()) {
            estuche = true;
        } else {
            estuche = false;
        }

        Ds_Portatil.dispose();

    }//GEN-LAST:event_Ds_portatilMouseClicked

    private void Ds_botonestacionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ds_botonestacionarioActionPerformed

    }//GEN-LAST:event_Ds_botonestacionarioActionPerformed

    private void Ds_botonestacionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ds_botonestacionarioMouseClicked

        numcon = Integer.parseInt(Ds_NumeroControles.getText());
        space = Integer.parseInt(Ds_Almacenamiento.getText());
        conex = Ds_Tipoconexion.getText();

        Ds_Estacionaria.dispose();


    }//GEN-LAST:event_Ds_botonestacionarioMouseClicked

    private void Ds_TabladeconsolasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ds_TabladeconsolasMouseClicked

        if (evt.isMetaDown()) {

            Ds_Menuprincipal.show(Ds_Tabladeconsolas, evt.getX(), evt.getY());

        }
        DefaultListModel modelo
                = (DefaultListModel) Ds_List.getModel();

        Ds_Tabladeconsolas.getSelectedRow();

        Consolas cons = (Consolas) consolas.get(Ds_Tabladeconsolas.getSelectedRow());

        for (int i = 0; i < cons.getJuegos().size(); i++) {
            modelo.addElement(i);
        }


    }//GEN-LAST:event_Ds_TabladeconsolasMouseClicked


    private void Ds_ListarJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ds_ListarJuegosActionPerformed
        Ds_ListarLosjuegos.pack();
        Ds_ListarLosjuegos.setModal(true);
        Ds_ListarLosjuegos.setLocationRelativeTo(null);
        Ds_ListarLosjuegos.setVisible(true);

        
        
        
        

    }//GEN-LAST:event_Ds_ListarJuegosActionPerformed

    private void Ds_JuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ds_JuegosMouseClicked


    }//GEN-LAST:event_Ds_JuegosMouseClicked

    private void Ds_noagregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ds_noagregadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ds_noagregadoActionPerformed

    private void Ds_botonagrgadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ds_botonagrgadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ds_botonagrgadoActionPerformed

    private void Ds_agregarjuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ds_agregarjuegosMouseClicked
        String nombreJuego, desc;
        double precioJ;
        Date fechaJ;
        String estado;
        int cantidad;
        boolean rentable, agregado;

        nombreJuego = Ds_Nombredelosjuegos.getText();
        desc = Ds_Descripcion.getText();
        fechaJ = Ds_Fechadeljuego.getDate();
        precioJ = Integer.parseInt(Ds_Preciodeljuego.getText());

        if (Ds_Estadonuevo.isSelected()) {
            estado = "Nuevo";
        } else {
            estado = "Viejo";
        }

        if (Ds_Norentable.isSelected()) {
            rentable = false;
        } else {
            rentable = true;

        }

        if (Ds_noagregado.isSelected()) {
            agregado = false;
        } else {
            agregado = true;
        }

        cantidad = (int) Ds_Cantidaddejuegos.getValue();

        Juegos j = new Juegos(nombreJuego, desc, fechaJ, precioJ, estado, rentable, agregado, cantidad);

        Consolas consola = (Consolas) consolas.get(Ds_Tabladeconsolas.getSelectedRow());

        consola.agregarJuego(j);


    }//GEN-LAST:event_Ds_agregarjuegosMouseClicked

    private void Ds_PantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ds_PantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ds_PantallaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        Ds_Juegos.pack();
        Ds_Juegos.setModal(true);
        Ds_Juegos.setLocationRelativeTo(null);
        Ds_Juegos.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Ds_Agregado;
    private javax.swing.JButton Ds_AgregarConsolas;
    private javax.swing.JTextField Ds_Almacenamiento;
    private javax.swing.JSpinner Ds_Anosuso;
    private javax.swing.JTextField Ds_Bateria;
    private javax.swing.JSpinner Ds_Cantidaddejuegos;
    private javax.swing.JTextArea Ds_Descripcion;
    private javax.swing.JMenuItem Ds_EliminarConsolas;
    private javax.swing.JDialog Ds_Estacionaria;
    private javax.swing.JRadioButton Ds_EstacionariaRadio;
    private javax.swing.ButtonGroup Ds_Estado;
    private javax.swing.JRadioButton Ds_Estadonuevo;
    private javax.swing.JRadioButton Ds_Estadousado;
    private javax.swing.JTextField Ds_Fabricante;
    private com.toedter.calendar.JCalendar Ds_Fechadeljuego;
    private javax.swing.JTextField Ds_Identificacion;
    private javax.swing.JDialog Ds_Juegos;
    private javax.swing.JSpinner Ds_Juegosdisponibles;
    private javax.swing.JList<String> Ds_List;
    private javax.swing.JMenuItem Ds_ListarJuegos;
    private javax.swing.JDialog Ds_ListarLosjuegos;
    private javax.swing.JPopupMenu Ds_Menuprincipal;
    private javax.swing.JTextField Ds_Modelo;
    private javax.swing.JMenuItem Ds_Modificarconsolas;
    private javax.swing.JTextField Ds_Nombredelosjuegos;
    private javax.swing.JRadioButton Ds_Norentable;
    private javax.swing.JTextField Ds_NumeroControles;
    private javax.swing.JTextField Ds_Pantalla;
    private javax.swing.JDialog Ds_Portatil;
    private javax.swing.JTextField Ds_Precio;
    private javax.swing.JTextField Ds_Preciodeljuego;
    private javax.swing.JRadioButton Ds_RadioPortatil;
    private javax.swing.ButtonGroup Ds_Rentable;
    private javax.swing.JRadioButton Ds_Rentableboton;
    private javax.swing.ButtonGroup Ds_Sekeccion;
    private javax.swing.JTable Ds_Tabladeconsolas;
    private javax.swing.ButtonGroup Ds_Tipobottongroup;
    private javax.swing.JTextField Ds_Tipoconexion;
    private javax.swing.JButton Ds_agregarjuegos;
    private javax.swing.JRadioButton Ds_botonagrgado;
    private javax.swing.JButton Ds_botonestacionario;
    private javax.swing.JRadioButton Ds_no;
    private javax.swing.JRadioButton Ds_noagregado;
    private javax.swing.JButton Ds_portatil;
    private javax.swing.JRadioButton Ds_si;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    ArrayList consolas = new ArrayList();

    String tampan;

    int bat;

    boolean estuche;

    int numcon;

    String conex;

    int space;

}
